/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    categories: Category;
    'landing-pages': LandingPage;
    resources: Resource;
    'app-dashboards': AppDashboard;
    'platform-content': PlatformContent;
    'faq-content': FaqContent;
    media: Media;
    modules: Module;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'app-dashboards': AppDashboardsSelect<false> | AppDashboardsSelect<true>;
    'platform-content': PlatformContentSelect<false> | PlatformContentSelect<true>;
    'faq-content': FaqContentSelect<false> | FaqContentSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'star-auras': StarAura;
  };
  globalsSelect: {
    'star-auras': StarAurasSelect<false> | StarAurasSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  name: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  relatedPosts?: (string | Post)[] | null;
  /**
   * Select a category related to this post.
   */
  relatedCategories?: (string | null) | Category;
  /**
   * Featured image for the post
   */
  heroImage?: (string | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  /**
   * Check this box to publish the post
   */
  isPublish?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  /**
   * Optional poster image to represent video files
   */
  poster?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: string;
  /**
   * Internal name (e.g., "Beta Landing", "Nillion Site")
   */
  name: string;
  /**
   * URL slug (e.g., "beta", "nillion")
   */
  slug: string;
  /**
   * Toggle to activate/deactivate this page
   */
  isActive?: boolean | null;
  /**
   * Configure Star Auras display for this page
   */
  starAuras?: {
    /**
     * Show Star Auras section on this page
     */
    includeStarAuras?: boolean | null;
  };
  /**
   * Build your page by adding and arranging blocks
   */
  blocks?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            isBannerVisible?: boolean | null;
            bannerText?: string | null;
            style?: {
              titleSize?: ('lg' | 'xl' | 'xxl') | null;
              alignment?: ('left' | 'center') | null;
            };
            bgMedia?: {
              image?: (string | null) | Media;
              logo?: (string | null) | Media;
              'brand-avatar'?: (string | null) | Media;
            };
            buttons?:
              | {
                  text: string;
                  /**
                   * Primary button style vs secondary
                   */
                  isPrimary?: boolean | null;
                  /**
                   * Large button size
                   */
                  isLarge?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            items?:
              | {
                  title: string;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  /**
                   * Enter emoji or icon class (e.g., 🚀, fa-rocket)
                   */
                  icon?: string | null;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            layout?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefits';
          }
        | {
            title?: string | null;
            items?:
              | {
                  title: string;
                  description: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  /**
                   * Logo/icon for this content item
                   */
                  logo: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-features';
          }
        | {
            /**
             * Button text for the guideline section
             */
            buttonText?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Brief description of the guidelines
             */
            guidelineBrief: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'guidelince';
          }
        | {
            title?: string | null;
            /**
             * Select FAQs to display in this section - vertical list format
             */
            faqs?:
              | {
                  /**
                   * Select FAQ - the question will show in the dropdown
                   */
                  faq: string | FaqContent;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Additional helping text for iOS users
             */
            helpingTextTestflight?: string | null;
            /**
             * Enable Android waitlist functionality
             */
            isAndroidWaitlistEnabled?: boolean | null;
            /**
             * Ask users for their social media handle
             */
            askSocialMediaHandle?: boolean | null;
            formFields?:
              | {
                  /**
                   * Field name (e.g., email, firstName)
                   */
                  name: string;
                  /**
                   * Display label (e.g., Email Address)
                   */
                  label: string;
                  type?: ('text' | 'email' | 'phone') | null;
                  required?: boolean | null;
                  placeholder?: string | null;
                  id?: string | null;
                }[]
              | null;
            submitText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signup';
          }
      )[]
    | null;
  seo?: {
    /**
     * SEO page title (appears in browser tab)
     */
    title?: string | null;
    /**
     * Meta description for search engines (max 160 chars)
     */
    description?: string | null;
    /**
     * Keywords separated by commas
     */
    keywords?: string | null;
    /**
     * Social sharing image (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-content".
 */
export interface FaqContent {
  id: string;
  /**
   * The FAQ question
   */
  question: string;
  /**
   * Auto-generated label combining question and tags for selection
   */
  label?: string | null;
  /**
   * The detailed answer to the question
   */
  answer: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Whether this FAQ is currently active/published
   */
  isActive?: boolean | null;
  metadata?: {
    /**
     * Tags for better searchability and organization
     */
    tags?: string[] | null;
    /**
     * Date when this FAQ was last reviewed for accuracy
     */
    lastReviewed?: string | null;
    /**
     * Internal notes or comments about this FAQ
     */
    internalNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: string;
  /**
   * Main page title displayed in header
   */
  title: string;
  /**
   * Brief description of the resource page
   */
  description?: string | null;
  /**
   * Select content from the platform content library
   */
  body?: (string | null) | PlatformContent;
  /**
   * Individual pages for each section with detailed content
   */
  subPages?:
    | {
        pageTitle: string;
        pageDescription?: string | null;
        /**
         * URL slug for this page (e.g., "what-is-rainfall")
         */
        pageSlug: string;
        /**
         * Select content from the platform content library
         */
        pageBody?: (string | null) | PlatformContent;
        id?: string | null;
      }[]
    | null;
  navigation?: {
    /**
     * Navigation items that reference sub-pages
     */
    items?:
      | {
          /**
           * Title shown in navigation
           */
          navTitle: string;
          /**
           * Should match the slug of a sub-page above
           */
          subPageReference?: string | null;
          active?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Overview sections like "What is Rainfall", "Getting Started" that link to sub-pages
   */
  overviewSections?:
    | {
        /**
         * Section title (e.g., "What is Rainfall")
         */
        sectionTitle: string;
        /**
         * Brief description of the section content
         */
        sectionDescription: string;
        /**
         * Slug of the sub-page this section links to (must match a sub-page slug above)
         */
        linkedSubPage: string;
        /**
         * Text for the section link (default: "Read more")
         */
        linkText?: string | null;
        /**
         * Display order of sections in overview
         */
        sectionOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  lastModified?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-content".
 */
export interface PlatformContent {
  id: string;
  /**
   * Display name for this content (e.g., "Website Terms of Use", "App Privacy Policy")
   */
  name: string;
  /**
   * title for this content (e.g., "Website Terms of Use", "App Privacy Policy")
   */
  title: string;
  /**
   * summury for this content (e.g., "Website Terms of Use", "App Privacy Policy")
   */
  summury: string;
  /**
   * Which platform this content is intended for
   */
  platform: 'website' | 'app' | 'both';
  /**
   * The rich text content
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Select FAQs to display for this platform content
   */
  faqs?:
    | {
        /**
         * Select FAQ — question shows with tags
         */
        faq: string | FaqContent;
        id?: string | null;
      }[]
    | null;
  /**
   * Whether this content is currently active/published
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-dashboards".
 */
export interface AppDashboard {
  id: string;
  /**
   * Dashboard title for internal reference
   */
  title: string;
  /**
   * Unique identifier for API reference (e.g., R.1_Dashboard)
   */
  identifier: string;
  /**
   * Select modules for this dashboard - vertical list format
   */
  modules?:
    | {
        module: string | Module;
        order?: number | null;
        overrides?: {
          title?: string | null;
          uiStyle?: ('default' | 'light' | 'dark') | null;
          dismissible?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Select FAQs for this dashboard - vertical list format
   */
  faqs?:
    | {
        faq: string | FaqContent;
        id?: string | null;
      }[]
    | null;
  dashboardSettings?: {
    layout?: ('grid' | 'list' | 'custom') | null;
    theme?: ('light' | 'dark' | 'auto') | null;
    refreshInterval?: number | null;
  };
  targetAudience?: {
    userRoles?: string[] | null;
    appVersions?: string[] | null;
    platforms?: ('ios' | 'android' | 'web')[] | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: string;
  /**
   * Module name for identification and reuse
   */
  name: string;
  /**
   * Unique identifier for this module (auto-generated if empty)
   */
  slug?: string | null;
  backgroundImage?: (string | null) | Media;
  /**
   * Display title for the module (can be different from name)
   */
  title?: string | null;
  /**
   * Visual style/layout of the module
   */
  style: 'activities' | 'rainmaker' | 'timeline' | 'full' | 'button1' | 'card' | 'banner';
  /**
   * Category for organizing modules (e.g., "Navigation", "Content", "Actions")
   */
  category?: string | null;
  /**
   * UI theme for the module
   */
  uiStyle?: ('light' | 'dark') | null;
  /**
   * Can users dismiss/close this module?
   */
  dismissible?: boolean | null;
  /**
   * Start date for time-based modules
   */
  startDate?: string | null;
  /**
   * Main content for the module
   */
  body?: (string | null) | PlatformContent;
  /**
   * Background image for visual modules
   */
  bgImage?: (string | null) | Media;
  /**
   * External image URL (alternative to uploaded image)
   */
  bgImageUrl?: string | null;
  /**
   * Items for list-based modules
   */
  listItems?:
    | {
        title: string;
        description?: string | null;
        timestamp?: string | null;
        status?: ('active' | 'completed' | 'pending' | 'cancelled') | null;
        id?: string | null;
      }[]
    | null;
  action: {
    /**
     * Select the type of action this module should perform
     */
    type: 'showContent' | 'email' | 'openWebPage' | 'deepLink' | 'none';
    emailAddress?: string | null;
    webPageURL?: string | null;
    webPageOptions?: ('same' | 'new' | 'modal') | null;
    /**
     * App deep link URL (e.g., myapp://screen/detail)
     */
    deepLinkURL?: string | null;
    content?: (string | null) | PlatformContent;
  };
  /**
   * Whether this module is currently active/available for use
   */
  isActive?: boolean | null;
  metadata?: {
    /**
     * Internal description or notes about this module
     */
    description?: string | null;
    /**
     * Tags for better organization and searchability
     */
    tags?: string[] | null;
    /**
     * Version number or identifier
     */
    version?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: string | LandingPage;
      } | null)
    | ({
        relationTo: 'resources';
        value: string | Resource;
      } | null)
    | ({
        relationTo: 'app-dashboards';
        value: string | AppDashboard;
      } | null)
    | ({
        relationTo: 'platform-content';
        value: string | PlatformContent;
      } | null)
    | ({
        relationTo: 'faq-content';
        value: string | FaqContent;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'modules';
        value: string | Module;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  relatedPosts?: T;
  relatedCategories?: T;
  heroImage?: T;
  body?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  publishedAt?: T;
  isPublish?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  starAuras?:
    | T
    | {
        includeStarAuras?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              isBannerVisible?: T;
              bannerText?: T;
              style?:
                | T
                | {
                    titleSize?: T;
                    alignment?: T;
                  };
              bgMedia?:
                | T
                | {
                    image?: T;
                    logo?: T;
                    'brand-avatar'?: T;
                  };
              buttons?:
                | T
                | {
                    text?: T;
                    isPrimary?: T;
                    isLarge?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        benefits?:
          | T
          | {
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    image?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        'content-features'?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    logo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        guidelince?:
          | T
          | {
              buttonText?: T;
              content?: T;
              guidelineBrief?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              faqs?:
                | T
                | {
                    faq?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        signup?:
          | T
          | {
              title?: T;
              description?: T;
              helpingTextTestflight?: T;
              isAndroidWaitlistEnabled?: T;
              askSocialMediaHandle?: T;
              formFields?:
                | T
                | {
                    name?: T;
                    label?: T;
                    type?: T;
                    required?: T;
                    placeholder?: T;
                    id?: T;
                  };
              submitText?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  body?: T;
  subPages?:
    | T
    | {
        pageTitle?: T;
        pageDescription?: T;
        pageSlug?: T;
        pageBody?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        items?:
          | T
          | {
              navTitle?: T;
              subPageReference?: T;
              active?: T;
              id?: T;
            };
      };
  overviewSections?:
    | T
    | {
        sectionTitle?: T;
        sectionDescription?: T;
        linkedSubPage?: T;
        linkText?: T;
        sectionOrder?: T;
        id?: T;
      };
  lastModified?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-dashboards_select".
 */
export interface AppDashboardsSelect<T extends boolean = true> {
  title?: T;
  identifier?: T;
  modules?:
    | T
    | {
        module?: T;
        order?: T;
        overrides?:
          | T
          | {
              title?: T;
              uiStyle?: T;
              dismissible?: T;
            };
        id?: T;
      };
  faqs?:
    | T
    | {
        faq?: T;
        id?: T;
      };
  dashboardSettings?:
    | T
    | {
        layout?: T;
        theme?: T;
        refreshInterval?: T;
      };
  targetAudience?:
    | T
    | {
        userRoles?: T;
        appVersions?: T;
        platforms?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-content_select".
 */
export interface PlatformContentSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  summury?: T;
  platform?: T;
  content?: T;
  faqs?:
    | T
    | {
        faq?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-content_select".
 */
export interface FaqContentSelect<T extends boolean = true> {
  question?: T;
  label?: T;
  answer?: T;
  isActive?: T;
  metadata?:
    | T
    | {
        tags?: T;
        lastReviewed?: T;
        internalNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  poster?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  backgroundImage?: T;
  title?: T;
  style?: T;
  category?: T;
  uiStyle?: T;
  dismissible?: T;
  startDate?: T;
  body?: T;
  bgImage?: T;
  bgImageUrl?: T;
  listItems?:
    | T
    | {
        title?: T;
        description?: T;
        timestamp?: T;
        status?: T;
        id?: T;
      };
  action?:
    | T
    | {
        type?: T;
        emailAddress?: T;
        webPageURL?: T;
        webPageOptions?: T;
        deepLinkURL?: T;
        content?: T;
      };
  isActive?: T;
  metadata?:
    | T
    | {
        description?: T;
        tags?: T;
        version?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "star-auras".
 */
export interface StarAura {
  id: string;
  /**
   * Main page title
   */
  title: string;
  /**
   * Subtitle or tagline for the page
   */
  subtitle?: string | null;
  /**
   * Background image for the page
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Foreground/hero image for the page
   */
  foregroundImage?: (string | null) | Media;
  /**
   * Select content from the platform content library
   */
  content?: (string | null) | PlatformContent;
  /**
   * Disclaimer text to display on the page
   */
  disclaimerText?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "star-auras_select".
 */
export interface StarAurasSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  foregroundImage?: T;
  content?: T;
  disclaimerText?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: string | Post;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
